[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "textual-budget-app"
dynamic = ["version"]
description = "Budget Tracking TUI Application"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
  { name = "Davin Shearer", email = "scholarsmate@users.noreply.github.com" }
]
keywords = ["tui", "textual", "terminal", "budget-tracker", "finance", "cli"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: End Users/Desktop",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Office/Business",
  "Topic :: Utilities",
]

dependencies = [
  "textual>=6.2.1",
  "bcrypt>=5.0.0",
  "cryptography>=43.0.3",
  "rich>=14.1.0",
  "platformdirs>=3.0.0",
]

[project.scripts]
"budget-app" = "budget_app.main:main"

[project.urls]
Homepage = "https://github.com/scholarsmate/textual-examples"
Repository = "https://github.com/scholarsmate/textual-examples"
Issues = "https://github.com/scholarsmate/textual-examples/issues"

[tool.hatch.build]
include = [
  "README.md",
  "LICENSE",
]

[tool.hatch.build.targets.sdist]
include = [
  "src/**",
  "README.md",
  "LICENSE",
]

[tool.hatch.build.targets.wheel.force-include]
"src/budget_app" = "budget_app"
"src/tui_common" = "tui_common"

[tool.hatch.version]
source = "regex"
path = "src/VERSION"
pattern = "^(?P<version>.+)$"
